// Code generated by MockGen. DO NOT EDIT.
// Source: mock_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"
	models "sync-algo/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// UpdateStatuses mocks base method.
func (m *MockService) UpdateStatuses(ctx context.Context, algoStatuses *models.AlgoStatuses) (*models.AlgoStatuses, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatuses", ctx, algoStatuses)
	ret0, _ := ret[0].(*models.AlgoStatuses)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatuses indicates an expected call of UpdateStatuses.
func (mr *MockServiceMockRecorder) UpdateStatuses(ctx, algoStatuses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatuses", reflect.TypeOf((*MockService)(nil).UpdateStatuses), ctx, algoStatuses)
}
