CREATE TABLE IF NOT EXISTS clients (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    version INT DEFAULT 1,
    image VARCHAR(255) DEFAULT '',
    cpu VARCHAR(50) DEFAULT '',
    memory VARCHAR(50) DEFAULT '',
    priority FLOAT DEFAULT 1.0,
    need_restart BOOLEAN DEFAULT FALSE,
    spawned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS algorithm_statuses (
    id SERIAL PRIMARY KEY,
    client_id INT REFERENCES clients(id) UNIQUE,
    vwap BOOLEAN DEFAULT FALSE,
    twap BOOLEAN DEFAULT FALSE,
    hft BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE
);
